<#
.SYNOPSIS
    Shared helpers for diff-based C# linters (Test-LineLength.ps1, Test-EAndSSpelling.ps1).
    Dot-source from a sibling script: `. (Join-Path $PSScriptRoot '_Diff-Helpers.ps1')`.
#>

function Test-IsAutoGenerated([string]$file) {
    # Path-based shortcuts — catches deleted files and files we can't read.
    if ($file -match '\.Designer\.cs$') { return $true }
    if ($file -match '_Generated\.cs$') { return $true }
    if ($file -match 'ContextModelSnapshot\.cs$') { return $true }

    # Content marker — the canonical "<auto-generated>" header used by EF, Swyfft
    # code gen, and most other code generators. Caught surgically rather than via path
    # exclusions so future generators (or one-off generated files) are handled too.
    if (Test-Path -LiteralPath $file) {
        $head = Get-Content -LiteralPath $file -TotalCount 10 -ErrorAction SilentlyContinue
        if ($head -and ($head -join "`n") -match '<auto-generated>') { return $true }
    }

    return $false
}

<#
.SYNOPSIS
    Streams added/modified .cs lines from the unified diff, plus every line of untracked
    .cs files in local mode. Auto-generated files are skipped.

.OUTPUTS
    [PSCustomObject] with File, Line, Content properties — one per scan candidate.
#>
function Get-CSharpDiffLines {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [ValidateSet('local', 'branch')]
        [string]$Mode
    )

    if ($Mode -eq 'local') {
        $diffArgs = @('diff', '--unified=0', 'HEAD')
    }
    else {
        $diffArgs = @('diff', '--unified=0', 'development...HEAD')
    }

    $diff = & git @diffArgs

    $currentFile = $null
    $skipCurrentFile = $false
    $lineNum = 0

    foreach ($line in $diff) {
        # File header: +++ b/path/to/file
        if ($line -match '^\+\+\+ b/(.+)$') {
            $currentFile = $Matches[1]
            # Skip non-.cs files (linters are C#-specific) and auto-generated files.
            $skipCurrentFile = (-not $currentFile.EndsWith('.cs')) -or (Test-IsAutoGenerated $currentFile)
            continue
        }

        if ($skipCurrentFile) {
            continue
        }

        # Hunk header: @@ -X,Y +Z,W @@  (W is optional, defaults to 1)
        if ($line -match '^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@') {
            $lineNum = [int]$Matches[1] - 1
            continue
        }

        # Added line (excludes the +++ header which we matched above)
        if ($line.StartsWith('+')) {
            $lineNum++
            [PSCustomObject]@{
                File    = $currentFile
                Line    = $lineNum
                Content = $line.Substring(1)
            }
        }
        # `-` removed line — does NOT advance new-file counter, skip
        # context line — never appears with --unified=0
    }

    # Untracked .cs files don't show up in `git diff` — scan them in full (local mode only;
    # branch mode compares committed history where untracked files aren't relevant).
    if ($Mode -eq 'local') {
        $untracked = & git ls-files --others --exclude-standard
        foreach ($file in $untracked) {
            if (-not $file.EndsWith('.cs')) { continue }
            if (Test-IsAutoGenerated $file) { continue }

            $contents = Get-Content -LiteralPath $file -ErrorAction SilentlyContinue
            if (-not $contents) { continue }

            $i = 0
            foreach ($line in $contents) {
                $i++
                [PSCustomObject]@{
                    File    = $file
                    Line    = $i
                    Content = $line
                }
            }
        }
    }
}
